public class Arthimaticcalculations{
    

    public integer Addition(integer x, integer y) {
        integer z = 0;
        z = x+y;
        system.debug(' Sum of two variables ' + z);
        return z;
    }
    public integer Addition(integer x, integer y, integer z, integer m, integer k) {
        integer w = 0;
        w = x+y+z+m+k;
        system.debug(' Sum of five variables ' + w);
        return w;
    }

}