public  class Calculationswithsame {
    public integer Addition(integer a, integer b) {
        integer z = 0;
        z = a+b;
        system.debug(' Sum of two variables ' + z);
        return z;
    }
    public integer Addition(integer a, integer b, integer v, integer n) {
        integer z = 0;
        z = a+b+v+n;
        system.debug(' Sum of two variables ' + z);
        return z;

    }
}
