Arthimaticcalculations are = new Arthimaticcalculations();
integer sum = are.Addition(10, 15);
system.debug('sum = ' + sum);

integer dm = are.Addition(5, 4, 3, 2, 1);
system.debug(' sum = ' + dm);

Calculationswithsame sir = new Calculationswithsame();
integer ok = sir.Addition(1, 3);
system.debug(' Sum will be = ' + ok);

integer ok1 = sir.Addition(1, 3, 4, 6);
system.debug(' Sum will be = ' + ok1);